In [1]:
import pandas as pd
import numpy as np

from matplotlib import pyplot as plt
%matplotlib inline

import seaborn as sb
sb.set_style('darkgrid')

import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import scale
from sklearn import metrics
from sklearn.metrics import recall_score,accuracy_score,precision_score,classification_report
from sklearn.metrics import confusion_matrix
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [7]:
iris=pd.read_csv("Iris.csv")
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
6      7            4.6           3.4            1.4           0.3   
7      8            5.0           3.4            1.5           0.2   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
10    11            5.4           3.7            1.5           0.2   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            4.3           3.0            1.1           0.1   
14    15            5.8           4.0            1.2           0.2   
15    16            5.7           4.4            1.5           0.4   
16    17            5.4           3.9            1.3           0.4   
17    18            5.1           3.5            1.4           0.3   
18    19            5.7           3.8            1.7           0.3   
19    20            5.1           3.8            1.5           0.3   
20    21            5.4           3.4            1.7           0.2   
21    22            5.1           3.7            1.5           0.4   
22    23            4.6           3.6            1.0           0.2   
23    24            5.1           3.3            1.7           0.5   
24    25            4.8           3.4            1.9           0.2   
25    26            5.0           3.0            1.6           0.2   
26    27            5.0           3.4            1.6           0.4   
27    28            5.2           3.5            1.5           0.2   
28    29            5.2           3.4            1.4           0.2   
29    30            4.7           3.2            1.6           0.2   
..   ...            ...           ...            ...           ...   
120  121            6.9           3.2            5.7           2.3   
121  122            5.6           2.8            4.9           2.0   
122  123            7.7           2.8            6.7           2.0   
123  124            6.3           2.7            4.9           1.8   
124  125            6.7           3.3            5.7           2.1   
125  126            7.2           3.2            6.0           1.8   
126  127            6.2           2.8            4.8           1.8   
127  128            6.1           3.0            4.9           1.8   
128  129            6.4           2.8            5.6           2.1   
129  130            7.2           3.0            5.8           1.6   
130  131            7.4           2.8            6.1           1.9   
131  132            7.9           3.8            6.4           2.0   
132  133            6.4           2.8            5.6           2.2   
133  134            6.3           2.8            5.1           1.5   
134  135            6.1           2.6            5.6           1.4   
135  136            7.7           3.0            6.1           2.3   
136  137            6.3           3.4            5.6           2.4   
137  138            6.4           3.1            5.5           1.8   
138  139            6.0           3.0            4.8           1.8   
139  140            6.9           3.1            5.4           2.1   
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146        

In [8]:
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [10]:
iris['Species'].value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        50
Name: Species, dtype: int64

In [14]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species', 'iris'],
      dtype='object')

In [11]:
le_iris=LabelEncoder()
le_iris=le_iris.fit(iris['Species'])
iris['iris']=le_iris.transform(iris['Species'])

In [17]:
X=iris[['SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y=iris[['Species']]

In [18]:
scaler=MinMaxScaler()
nX=pd.DataFrame(scaler.fit_transform(X))


In [19]:
nX.columns=X.columns

In [20]:
nX

SepalWidthCm  PetalLengthCm  PetalWidthCm
0        0.625000       0.067797      0.041667
1        0.416667       0.067797      0.041667
2        0.500000       0.050847      0.041667
3        0.458333       0.084746      0.041667
4        0.666667       0.067797      0.041667
5        0.791667       0.118644      0.125000
6        0.583333       0.067797      0.083333
7        0.583333       0.084746      0.041667
8        0.375000       0.067797      0.041667
9        0.458333       0.084746      0.000000
10       0.708333       0.084746      0.041667
11       0.583333       0.101695      0.041667
12       0.416667       0.067797      0.000000
13       0.416667       0.016949      0.000000
14       0.833333       0.033898      0.041667
15       1.000000       0.084746      0.125000
16       0.791667       0.050847      0.125000
17       0.625000       0.067797      0.083333
18       0.750000       0.118644      0.083333
19       0.750000       0.084746      0.083333
20       0.583333       0.118644      0.041667
21       0.708333       0.084746      0.125000
22       0.666667       0.000000      0.041667
23       0.541667       0.118644      0.166667
24       0.583333       0.152542      0.041667
25       0.416667       0.101695      0.041667
26       0.583333       0.101695      0.125000
27       0.625000       0.084746      0.041667
28       0.583333       0.067797      0.041667
29       0.500000       0.101695      0.041667
..            ...            ...           ...
120      0.500000       0.796610      0.916667
121      0.333333       0.661017      0.791667
122      0.333333       0.966102      0.791667
123      0.291667       0.661017      0.708333
124      0.541667       0.796610      0.833333
125      0.500000       0.847458      0.708333
126      0.333333       0.644068      0.708333
127      0.416667       0.661017      0.708333
128      0.333333       0.779661      0.833333
129      0.416667       0.813559      0.625000
130      0.333333       0.864407      0.750000
131      0.750000       0.915254      0.791667
132      0.333333       0.779661      0.875000
133      0.333333       0.694915      0.583333
134      0.250000       0.779661      0.541667
135      0.416667       0.864407      0.916667
136      0.583333       0.779661      0.958333
137      0.458333       0.762712      0.708333
138      0.416667       0.644068      0.708333
139      0.458333       0.745763      0.833333
140      0.458333       0.779661      0.958333
141      0.458333       0.694915      0.916667
142      0.291667       0.694915      0.750000
143      0.500000       0.830508      0.916667
144      0.541667       0.796610      1.000000
145      0.416667       0.711864      0.916667
146      0.208333       0.677966      0.750000
147      0.416667       0.711864      0.791667
148      0.583333       0.745763      0.916667
149      0.416667       0.694915      0.708333

[150 rows x 3 columns]

In [21]:
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
6      7            4.6           3.4            1.4           0.3   
7      8            5.0           3.4            1.5           0.2   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
10    11            5.4           3.7            1.5           0.2   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            4.3           3.0            1.1           0.1   
14    15            5.8           4.0            1.2           0.2   
15    16            5.7           4.4            1.5           0.4   
16    17            5.4           3.9            1.3           0.4   
17    18            5.1           3.5            1.4           0.3   
18    19            5.7           3.8            1.7           0.3   
19    20            5.1           3.8            1.5           0.3   
20    21            5.4           3.4            1.7           0.2   
21    22            5.1           3.7            1.5           0.4   
22    23            4.6           3.6            1.0           0.2   
23    24            5.1           3.3            1.7           0.5   
24    25            4.8           3.4            1.9           0.2   
25    26            5.0           3.0            1.6           0.2   
26    27            5.0           3.4            1.6           0.4   
27    28            5.2           3.5            1.5           0.2   
28    29            5.2           3.4            1.4           0.2   
29    30            4.7           3.2            1.6           0.2   
..   ...            ...           ...            ...           ...   
120  121            6.9           3.2            5.7           2.3   
121  122            5.6           2.8            4.9           2.0   
122  123            7.7           2.8            6.7           2.0   
123  124            6.3           2.7            4.9           1.8   
124  125            6.7           3.3            5.7           2.1   
125  126            7.2           3.2            6.0           1.8   
126  127            6.2           2.8            4.8           1.8   
127  128            6.1           3.0            4.9           1.8   
128  129            6.4           2.8            5.6           2.1   
129  130            7.2           3.0            5.8           1.6   
130  131            7.4           2.8            6.1           1.9   
131  132            7.9           3.8            6.4           2.0   
132  133            6.4           2.8            5.6           2.2   
133  134            6.3           2.8            5.1           1.5   
134  135            6.1           2.6            5.6           1.4   
135  136            7.7           3.0            6.1           2.3   
136  137            6.3           3.4            5.6           2.4   
137  138            6.4           3.1            5.5           1.8   
138  139            6.0           3.0            4.8           1.8   
139  140            6.9           3.1            5.4           2.1   
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146        

In [12]:
y

iris
0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
..    ...
120     2
121     2
122     2
123     2
124     2
125     2
126     2
127     2
128     2
129     2
130     2
131     2
132     2
133     2
134     2
135     2
136     2
137     2
138     2
139     2
140     2
141     2
142     2
143     2
144     2
145     2
146     2
147     2
148     2
149     2

[150 rows x 1 columns]

In [22]:
trainnX,testnX,trainy,testy=train_test_split(nX,y,test_size=0.2,random_state=4)

In [23]:
trainnX.shape

(120, 3)

In [24]:
pca=PCA(n_components=2)
trainnX=pca.fit_transform(trainnX)
testnX=pca.transform(testnX)

In [25]:
explained_variance=pca.explained_variance_ratio_

In [26]:
print(explained_variance)

[0.85876719 0.12513366]


In [28]:
dec=DecisionTreeClassifier()
model=dec.fit(trainnX,trainy)


In [29]:
preds=model.predict(testnX)

In [30]:
preds

array(['Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica'],
      dtype=object)

In [31]:
model.score(testnX,testy)

0.9333333333333333

In [32]:
cm=confusion_matrix(testy,preds)
print(cm)

[[16  0  0]
 [ 0  4  1]
 [ 0  1  8]]
